//
//  CreateRecordView.swift
//  SpatiumDDI
//

import SpatiumAPI
import SwiftUI

/// Adding one record to a zone.
///
/// The sibling of allocating an address: that path publishes an A record as
/// part of taking the address, and this is for everything that isn't tied to an
/// IPAM row — a CNAME for a service, a TXT for a verification, an MX.
///
/// Creating only. Editing or deleting a live record is how a phone becomes a
/// way to cause an outage, and both want their own discussion and probably a
/// typed confirmation; a record that was only added can be removed from the web
/// console by whoever notices.
struct CreateRecordView: View {
    let session: ControlPlaneSession
    let group: Components.Schemas.ServerGroupResponse
    let zone: Components.Schemas.ZoneResponse
    let onCreated: (Components.Schemas.RecordResponse) -> Void
    let onDismiss: () -> Void

    @State private var model: CreateRecordModel
    @State private var isConfirming = false

    init(
        session: ControlPlaneSession,
        group: Components.Schemas.ServerGroupResponse,
        zone: Components.Schemas.ZoneResponse,
        onCreated: @escaping (Components.Schemas.RecordResponse) -> Void,
        onDismiss: @escaping () -> Void
    ) {
        self.session = session
        self.group = group
        self.zone = zone
        self.onCreated = onCreated
        self.onDismiss = onDismiss
        _model = State(initialValue: CreateRecordModel(session: session, group: group, zone: zone))
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    LabeledContent("Zone", value: zone.name)
                    LabeledContent("Group", value: group.name)
                    LabeledContent("Serial", value: String(zone.lastSerial))
                }

                if zone.tailscaleTenantId != nil {
                    // Known in advance, so said in advance. The server refuses
                    // this with a 422 and the reconciler would overwrite it
                    // anyway; letting the operator fill in a form first would
                    // waste the only part of this that takes effort.
                    Section {
                        Label(
                            "This zone is generated by the Tailscale integration. Its records are managed by the reconciler and can't be edited here.",
                            systemImage: "lock.fill"
                        )
                        .foregroundStyle(.orange)
                    }
                } else {
                    recordSection
                    structuredSection
                    outcomeSection

                    // Why Save is refusing, said where the fields are rather
                    // than beside a button that is now in the bar. Without it a
                    // disabled Save is a dead end with no stated reason.
                    if !model.hasCreated {
                        Section {
                            if let problem = model.localProblem {
                                Label(problem, systemImage: "exclamationmark.triangle.fill")
                                    .font(.footnote)
                                    .foregroundStyle(.orange)
                            }
                        } footer: {
                            Text(
                                "The zone's serial is bumped and the change is pushed to every server in the group."
                            )
                        }
                    }
                }
            }
            .navigationTitle("New Record")
            .dismissableKeyboard()
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel", role: .cancel, action: onDismiss)
                        .disabled(model.isSending)
                }
                // In the bar for the same reason as the allocate sheet: at the
                // foot of the form it is the one control the keyboard covers.
                if !model.hasCreated, zone.tailscaleTenantId == nil {
                    ToolbarItem(placement: .confirmationAction) {
                        if model.isSending {
                            ProgressView()
                        } else {
                            Button("Save") { isConfirming = true }
                                .disabled(!model.canSubmit)
                        }
                    }
                }
            }
            // An alert, for the same reason as the allocate sheet: a dialog
            // raised from a toolbar button becomes a tailed popover over the
            // form, and the record line is the thing that must be readable.
            .alert("Create this record?", isPresented: $isConfirming) {
                Button("Cancel", role: .cancel) {}
                Button("Create") { Task { await submit() } }
            } message: {
                // The record as it will be written, in zone-file order — the
                // form an operator reads without translating.
                Text(verbatim: model.confirmationSummary)
            }
        }
        .interactiveDismissDisabled(model.isSending)
    }

    @ViewBuilder
    private var recordSection: some View {
        Section {
            Picker("Type", selection: $model.recordType) {
                ForEach(CreateRecordModel.offeredTypes, id: \.self) { type in
                    Text(verbatim: type).tag(type)
                }
            }
            TextField("Name", text: $model.name)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .font(.body.monospaced())
            TextField(model.valuePlaceholder, text: $model.value, axis: .vertical)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .font(.body.monospaced())
                .lineLimit(1...4)
            LabeledContent("TTL") {
                TextField(String(zone.ttl), text: $model.ttl)
                    .keyboardType(.numberPad)
                    .multilineTextAlignment(.trailing)
            }
        } header: {
            Text("Record")
        } footer: {
            VStack(alignment: .leading, spacing: 4) {
                Text("Will be created as \(model.fqdn)")
                    .font(.footnote.monospaced())
                Text(
                    "Use @ for the zone itself. Leave the TTL empty to inherit the zone's \(zone.ttl) seconds."
                )
            }
        }
    }

    @ViewBuilder
    private var structuredSection: some View {
        if model.usesPriority || model.usesWeightAndPort {
            Section {
                if model.usesPriority {
                    LabeledContent("Priority") {
                        TextField(model.recordType == "MX" ? "10" : "0", text: $model.priority)
                            .keyboardType(.numberPad)
                            .multilineTextAlignment(.trailing)
                    }
                }
                if model.usesWeightAndPort {
                    LabeledContent("Weight") {
                        TextField("0", text: $model.weight)
                            .keyboardType(.numberPad)
                            .multilineTextAlignment(.trailing)
                    }
                    LabeledContent("Port") {
                        TextField("443", text: $model.port)
                            .keyboardType(.numberPad)
                            .multilineTextAlignment(.trailing)
                    }
                }
            } header: {
                Text(model.recordType == "SRV" ? "Service" : "Preference")
            } footer: {
                if model.recordType == "SRV" {
                    // The server rejects a partial SRV rather than writing one
                    // that renders as `prio 0 0 target` on the wire.
                    Text("An SRV is priority, weight, port and target. All three numbers are required.")
                } else {
                    Text("Lower is preferred. Left empty, the server uses 10.")
                }
            }
        }
    }

    @ViewBuilder
    private var outcomeSection: some View {
        switch model.submission {
        case .idle, .sending:
            EmptyView()
        case .failed(let message):
            Section("Not created") {
                Label(message, systemImage: "xmark.octagon.fill").foregroundStyle(.red)
            }
        case .created:
            // Dismissed on success; on screen for one frame at most.
            EmptyView()
        }
    }

    private func submit() async {
        guard let created = await model.submit() else { return }
        // Back to the zone, which refetches — the list is a better report of
        // what was written than a banner describing it.
        onCreated(created)
        onDismiss()
    }
}

// MARK: - Model

@MainActor
@Observable
final class CreateRecordModel {
    enum Submission: Equatable {
        case idle
        case sending
        case failed(FailureMessage)
        case created(Components.Schemas.RecordResponse)

        static func == (lhs: Submission, rhs: Submission) -> Bool {
            switch (lhs, rhs) {
            case (.idle, .idle), (.sending, .sending): true
            case (.failed(let l), .failed(let r)): l == r
            case (.created(let l), .created(let r)): l.id == r.id
            default: false
            }
        }
    }

    /// What is worth authoring from a phone.
    ///
    /// The platform accepts more — DNSKEY, NAPTR, SVCB and the rest — but those
    /// are structured rdata nobody types correctly on a handset, and getting
    /// one wrong publishes it. They stay desktop work.
    static let offeredTypes = ["A", "AAAA", "CNAME", "TXT", "MX", "SRV", "NS", "PTR", "CAA"]

    var recordType = "A" { didSet { if recordType != oldValue { submission = .idle } } }
    var name = ""
    var value = ""
    var ttl = ""
    var priority = ""
    var weight = ""
    var port = ""

    private(set) var submission: Submission = .idle

    private let session: ControlPlaneSession
    private let group: Components.Schemas.ServerGroupResponse
    private let zone: Components.Schemas.ZoneResponse

    init(
        session: ControlPlaneSession,
        group: Components.Schemas.ServerGroupResponse,
        zone: Components.Schemas.ZoneResponse
    ) {
        self.session = session
        self.group = group
        self.zone = zone
        // A reverse zone is a zone of PTRs; starting it on A would be wrong
        // every time.
        if zone.kind == "reverse" { self.recordType = "PTR" }
    }

    var isSending: Bool { submission == .sending }

    /// Whether this sheet has already written something. A second tap on a form
    /// still holding the same values would publish the record twice — DNS has
    /// no duplicate check, so both would land in the RRset.
    var hasCreated: Bool {
        if case .created = submission { return true }
        return false
    }

    var usesPriority: Bool { recordType == "MX" || recordType == "SRV" }
    var usesWeightAndPort: Bool { recordType == "SRV" }

    var valuePlaceholder: String {
        switch recordType {
        case "A": "10.0.1.42"
        case "AAAA": "2001:db8::42"
        case "CNAME", "NS", "PTR": "host.example.com."
        case "MX": "mail.example.com."
        case "SRV": "sipserver.example.com."
        case "CAA": "0 issue \"letsencrypt.org\""
        default: "value"
        }
    }

    private var trimmedName: String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? "@" : trimmed
    }

    private var trimmedValue: String { value.trimmingCharacters(in: .whitespacesAndNewlines) }

    var fqdn: String {
        let bare = zone.name.hasSuffix(".") ? String(zone.name.dropLast()) : zone.name
        return trimmedName == "@" ? bare : "\(trimmedName).\(bare)"
    }

    /// What is wrong before anything is sent — a courtesy, not a gate.
    ///
    /// The server validates all of this independently and its message is the
    /// authoritative one; saying it here saves a round trip on the two mistakes
    /// that are easy to make on a phone keyboard.
    var localProblem: LocalizedStringResource? {
        if trimmedValue.isEmpty { return nil }
        switch recordType {
        case "A" where IPFamily.of(trimmedValue) != .v4:
            return "An A record's value is a single IPv4 address."
        case "AAAA" where IPFamily.of(trimmedValue) != .v6:
            return "An AAAA record's value is a single IPv6 address."
        case "SRV" where [priority, weight, port].contains(where: \.isEmpty):
            return "An SRV needs a priority, a weight and a port."
        default:
            return nil
        }
    }

    var canSubmit: Bool {
        !trimmedValue.isEmpty && localProblem == nil && !isSending && !hasCreated
            && zone.tailscaleTenantId == nil
    }

    var confirmationSummary: String {
        var line = "\(fqdn)  \(ttlValue.map { "\($0)  " } ?? "")\(recordType)  "
        if let priority = intOrNil(priority), usesPriority { line += "\(priority) " }
        if usesWeightAndPort {
            if let weight = intOrNil(weight) { line += "\(weight) " }
            if let port = intOrNil(port) { line += "\(port) " }
        }
        line += trimmedValue
        return line
    }

    private var ttlValue: Int? { intOrNil(ttl) }

    private func intOrNil(_ text: String) -> Int? {
        Int(text.trimmingCharacters(in: .whitespacesAndNewlines))
    }

    func submit() async -> Components.Schemas.RecordResponse? {
        guard canSubmit else { return nil }
        submission = .sending

        let body = Components.Schemas.RecordCreate(
            name: trimmedName,
            port: usesWeightAndPort ? intOrNil(port) : nil,
            priority: usesPriority ? intOrNil(priority) : nil,
            recordType: recordType,
            ttl: ttlValue,
            value: trimmedValue,
            weight: usesWeightAndPort ? intOrNil(weight) : nil
        )

        do {
            let response = try await session.client
                .createRecordApiV1DnsGroupsGroupIdZonesZoneIdRecordsPost(
                    path: .init(groupId: group.id, zoneId: zone.id),
                    body: .json(body)
                )
            switch response {
            case .created(let created):
                let record = try created.body.json
                submission = .created(record)
                return record
            case .unprocessableContent:
                throw APIStatusError(status: 422)
            case .undocumented(let statusCode, let payload):
                throw await APIStatusError(status: statusCode, payload: payload)
            }
        } catch {
            // Records have no soft-conflict path — DNS has no duplicate check,
            // so a 409 here would be a real one — but the status recovery and
            // the write wording are the same problem either way.
            if case .failed(let message) = await WriteFailure.classify(error, forced: true) {
                submission = .failed(message)
            }
            return nil
        }
    }
}

/// Which family an address literal belongs to, if any.
///
/// Used to catch the two mistakes a phone keyboard makes easy — an IPv6 address
/// typed into an A record, and vice versa — before they cost a round trip.
nonisolated enum IPFamily {
    case v4, v6, neither

    static func of(_ text: String) -> IPFamily {
        var v4 = in_addr()
        if text.withCString({ inet_pton(AF_INET, $0, &v4) }) == 1 { return .v4 }
        var v6 = in6_addr()
        if text.withCString({ inet_pton(AF_INET6, $0, &v6) }) == 1 { return .v6 }
        return .neither
    }
}
