//
//  EditRecordView.swift
//  SpatiumDDI
//

import SpatiumAPI
import SwiftUI

/// Changing a record that is already being served.
///
/// The sharpest edge here is not the API, it is which records should be edited
/// at all:
///
/// - **Synthesised** zones and records (Tailscale, NetBird) are owned by a
///   reconciler. The server refuses with a 422 and would overwrite an edit
///   anyway, so this refuses first rather than taking the typing.
/// - **Auto-generated** records are the ones IPAM published for an address. The
///   server permits editing them and the next IPAM→DNS sync undoes it. That is
///   the server's answer to respect, not one to override — so it warns rather
///   than blocks, and says where the change really belongs.
///
/// `record_type` is absent from `RecordUpdate`: the type is immutable, which is
/// correct — an A that becomes a CNAME is a different record.
struct EditRecordView: View {
    let session: ControlPlaneSession
    let group: Components.Schemas.ServerGroupResponse
    let zone: Components.Schemas.ZoneResponse
    let record: Components.Schemas.RecordResponse
    let onSaved: (Components.Schemas.RecordResponse) -> Void
    let onDismiss: () -> Void

    @State private var model: EditRecordModel
    @State private var isConfirming = false

    init(
        session: ControlPlaneSession,
        group: Components.Schemas.ServerGroupResponse,
        zone: Components.Schemas.ZoneResponse,
        record: Components.Schemas.RecordResponse,
        onSaved: @escaping (Components.Schemas.RecordResponse) -> Void,
        onDismiss: @escaping () -> Void
    ) {
        self.session = session
        self.group = group
        self.zone = zone
        self.record = record
        self.onSaved = onSaved
        self.onDismiss = onDismiss
        _model = State(
            initialValue: EditRecordModel(session: session, group: group, zone: zone, record: record)
        )
    }

    private var isSynthesised: Bool { zone.tailscaleTenantId != nil || record.tailscaleTenantId != nil }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    LabeledContent("Zone", value: zone.name)
                    LabeledContent("Type") {
                        Badge(text: record.recordType, tint: .indigo)
                    }
                    LabeledContent("FQDN") {
                        Text(verbatim: record.fqdn).font(.footnote.monospaced())
                    }
                } footer: {
                    Text(
                        "A record's type can't be changed — an A that becomes a CNAME is a different record.")
                }

                if isSynthesised {
                    Section {
                        Label(
                            "This record is generated by an integration and managed by its reconciler. Changes here would be overwritten on the next sync, and the server refuses them.",
                            systemImage: "lock.fill"
                        )
                        .foregroundStyle(.orange)
                    }
                } else {
                    if record.autoGenerated {
                        Section {
                            Label(
                                "This record was published by IPAM for an address. Editing it here works, and the next IPAM sync will put it back — change the address instead.",
                                systemImage: "arrow.triangle.2.circlepath"
                            )
                            .font(.footnote)
                            .foregroundStyle(.orange)
                        }
                    }

                    editableSection
                    structuredSection
                    outcomeSection
                }
            }
            .navigationTitle("Edit Record")
            .navigationBarTitleDisplayMode(.inline)
            .dismissableKeyboard()
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel", role: .cancel, action: onDismiss)
                        .disabled(model.isSending)
                }
                if !isSynthesised {
                    ToolbarItem(placement: .confirmationAction) {
                        if model.isSending {
                            ProgressView()
                        } else {
                            Button("Save") { isConfirming = true }
                                .disabled(!model.canSave)
                        }
                    }
                }
            }
            .alert("Save changes to \(record.fqdn)?", isPresented: $isConfirming) {
                Button("Cancel", role: .cancel) {}
                Button("Save") { Task { await save() } }
            } message: {
                Text(verbatim: model.changeSummary)
            }
        }
        .interactiveDismissDisabled(model.isSending)
    }

    @ViewBuilder
    private var editableSection: some View {
        Section {
            TextField("Name", text: $model.name)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .font(.body.monospaced())
            TextField("Value", text: $model.value, axis: .vertical)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .font(.body.monospaced())
                .lineLimit(1...4)
            LabeledContent("TTL") {
                TextField(String(zone.ttl), text: $model.ttl)
                    .keyboardType(.numberPad)
                    .multilineTextAlignment(.trailing)
            }
        } header: {
            Text("Record")
        } footer: {
            if let problem = model.localProblem {
                Label(problem, systemImage: "exclamationmark.triangle.fill")
                    .foregroundStyle(.orange)
            } else {
                Text("Saving bumps the zone's serial and pushes to every server in the group.")
            }
        }
    }

    @ViewBuilder
    private var structuredSection: some View {
        if model.usesPriority || model.usesWeightAndPort {
            Section(model.usesWeightAndPort ? "Service" : "Preference") {
                if model.usesPriority {
                    LabeledContent("Priority") {
                        TextField("10", text: $model.priority)
                            .keyboardType(.numberPad)
                            .multilineTextAlignment(.trailing)
                    }
                }
                if model.usesWeightAndPort {
                    LabeledContent("Weight") {
                        TextField("0", text: $model.weight)
                            .keyboardType(.numberPad)
                            .multilineTextAlignment(.trailing)
                    }
                    LabeledContent("Port") {
                        TextField("443", text: $model.port)
                            .keyboardType(.numberPad)
                            .multilineTextAlignment(.trailing)
                    }
                }
            }
        }
    }

    @ViewBuilder
    private var outcomeSection: some View {
        if case .failed(let message) = model.submission {
            Section("Not saved") {
                Label(message, systemImage: "xmark.octagon.fill").foregroundStyle(.red)
            }
        }
    }

    private func save() async {
        guard let saved = await model.save() else { return }
        onSaved(saved)
        onDismiss()
    }
}

// MARK: - Model

@MainActor
@Observable
final class EditRecordModel {
    enum Submission: Equatable {
        case idle
        case sending
        case failed(FailureMessage)
        case saved
    }

    var name: String
    var value: String
    var ttl: String
    var priority: String
    var weight: String
    var port: String

    private(set) var submission: Submission = .idle

    private let session: ControlPlaneSession
    private let group: Components.Schemas.ServerGroupResponse
    private let zone: Components.Schemas.ZoneResponse
    private let record: Components.Schemas.RecordResponse
    private let original: [String: String]

    init(
        session: ControlPlaneSession,
        group: Components.Schemas.ServerGroupResponse,
        zone: Components.Schemas.ZoneResponse,
        record: Components.Schemas.RecordResponse
    ) {
        self.session = session
        self.group = group
        self.zone = zone
        self.record = record
        self.name = record.name
        self.value = record.value
        self.ttl = record.ttl.map(String.init) ?? ""
        self.priority = record.priority.map(String.init) ?? ""
        self.weight = record.weight.map(String.init) ?? ""
        self.port = record.port.map(String.init) ?? ""
        self.original = [
            "name": record.name,
            "value": record.value,
            "ttl": record.ttl.map(String.init) ?? "",
            "priority": record.priority.map(String.init) ?? "",
            "weight": record.weight.map(String.init) ?? "",
            "port": record.port.map(String.init) ?? "",
        ]
    }

    var isSending: Bool { submission == .sending }
    var usesPriority: Bool { record.recordType == "MX" || record.recordType == "SRV" }
    var usesWeightAndPort: Bool { record.recordType == "SRV" }

    private var current: [String: String] {
        [
            "name": trimmed(name), "value": trimmed(value), "ttl": trimmed(ttl),
            "priority": trimmed(priority), "weight": trimmed(weight), "port": trimmed(port),
        ]
    }

    var hasChanges: Bool { current != original }

    /// A courtesy check, matching the server's own rules for these types.
    var localProblem: LocalizedStringResource? {
        let candidate = trimmed(value)
        if candidate.isEmpty { return "A record needs a value." }
        switch record.recordType {
        case "A" where IPFamily.of(candidate) != .v4:
            return "An A record's value is a single IPv4 address."
        case "AAAA" where IPFamily.of(candidate) != .v6:
            return "An AAAA record's value is a single IPv6 address."
        case "SRV" where [priority, weight, port].contains(where: { trimmed($0).isEmpty }):
            return "An SRV needs a priority, a weight and a port."
        case "MX" where FieldChange.clears(from: original["priority"] ?? "", to: priority):
            return "An MX record needs a priority."
        default:
            break
        }
        // An emptied TTL would be omitted from the update, and the server
        // reads that as "unchanged" — see FieldChange.clears.
        if FieldChange.clears(from: original["ttl"] ?? "", to: ttl) {
            return
                "The app can't reset a record to the zone's TTL yet — only change it. Put a value back, or reset it in the web console."
        }
        return nil
    }

    var canSave: Bool { hasChanges && localProblem == nil && !isSending }

    var changeSummary: String {
        let labels = [
            "name": "Name", "value": "Value", "ttl": "TTL",
            "priority": "Priority", "weight": "Weight", "port": "Port",
        ]
        // Sorted so two runs of the same edit read the same way.
        return current.keys.sorted()
            .compactMap { key -> String? in
                guard let before = original[key], let after = current[key], before != after else {
                    return nil
                }
                let from = before.isEmpty ? String(localized: "empty") : before
                let to = after.isEmpty ? String(localized: "empty") : after
                return "\(labels[key] ?? key): \(from) → \(to)"
            }
            .joined(separator: "\n")
    }

    private func trimmed(_ text: String) -> String {
        text.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func intOrNil(_ text: String) -> Int? { Int(trimmed(text)) }

    func save() async -> Components.Schemas.RecordResponse? {
        guard canSave else { return nil }
        submission = .sending

        let body = Components.Schemas.RecordUpdate(
            name: trimmed(name),
            port: usesWeightAndPort ? intOrNil(port) : nil,
            priority: usesPriority ? intOrNil(priority) : nil,
            ttl: intOrNil(ttl),
            value: trimmed(value),
            weight: usesWeightAndPort ? intOrNil(weight) : nil
        )

        do {
            let response = try await session.client
                .updateRecordApiV1DnsGroupsGroupIdZonesZoneIdRecordsRecordIdPut(
                    path: .init(groupId: group.id, zoneId: zone.id, recordId: record.id),
                    body: .json(body)
                )
            switch response {
            case .ok(let ok):
                let saved = try ok.body.json
                submission = .saved
                return saved
            case .unprocessableContent:
                throw APIStatusError(status: 422)
            case .undocumented(let statusCode, let payload):
                throw await APIStatusError(status: statusCode, payload: payload)
            }
        } catch {
            if case .failed(let message) = await WriteFailure.classify(error, forced: true) {
                submission = .failed(message)
            }
            return nil
        }
    }
}

/// Removing a record that is being served right now.
///
/// Unlike an IPAM address, the soft delete here is genuinely restorable — it
/// stamps a `deletion_batch_id` and the row appears under Trash, which this app
/// already has a screen for. What it does *not* do is wait: the retraction is
/// pushed to the provider immediately, so the name stops resolving before this
/// sheet has finished dismissing. The copy says both halves.
@MainActor
@Observable
final class DeleteRecordModel: Identifiable {
    let id = UUID()
    private(set) var isDeleting = false
    private(set) var failure: FailureMessage?

    private let session: ControlPlaneSession
    private let group: Components.Schemas.ServerGroupResponse
    private let zone: Components.Schemas.ZoneResponse
    let record: Components.Schemas.RecordResponse

    init(
        session: ControlPlaneSession,
        group: Components.Schemas.ServerGroupResponse,
        zone: Components.Schemas.ZoneResponse,
        record: Components.Schemas.RecordResponse
    ) {
        self.session = session
        self.group = group
        self.zone = zone
        self.record = record
    }

    /// The apex is stored as "@" or "", and neither is typeable as a
    /// confirmation — the zone's own name is what the operator is looking at.
    var subject: String {
        record.name.isEmpty || record.name == "@" ? zone.name : record.name
    }

    var consequence: LocalizedStringResource {
        "\(record.fqdn) stops resolving as soon as this is sent — the retraction is pushed to every server in the group, not left for a later sync. The record can be restored from Trash."
    }

    var caution: FailureMessage? {
        if record.autoGenerated {
            return .app(
                "IPAM published this record for an address. Deleting it here leaves the address still claiming the name, and the next sync republishes it."
            )
        }
        return .server("\(record.recordType)  \(record.value)")
    }

    func delete() async -> Bool {
        isDeleting = true
        failure = nil
        do {
            let response = try await session.client
                .deleteRecordApiV1DnsGroupsGroupIdZonesZoneIdRecordsRecordIdDelete(
                    path: .init(groupId: group.id, zoneId: zone.id, recordId: record.id),
                    // Soft, always. Permanent skips the Trash row that is the
                    // only way back from a mistake made one-handed.
                    query: .init(permanent: false)
                )
            switch response {
            case .noContent:
                isDeleting = false
                return true
            case .unprocessableContent:
                throw APIStatusError(status: 422)
            case .undocumented(let statusCode, let payload):
                throw await APIStatusError(status: statusCode, payload: payload)
            }
        } catch {
            if case .failed(let message) = await WriteFailure.classify(error, forced: true) {
                failure = message
            }
            isDeleting = false
            return false
        }
    }
}
